services:
  postgres:
    image: bitnami/postgresql:latest
    environment:
      - POSTGRESQL_USERNAME=docker
      - POSTGRESQL_PASSWORD=docker
      - POSTGRESQL_DATABASE=brevly
    ports:
      - "5432:5432"
    volumes:
      - "./docker:/docker-entrypoint-initdb.d"
